### ISSUE TITLE
Java exceptions noted during interactive testing

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#423]
These were witnessed during my interactive testing last night.

```
20:46:11,846 ERROR GeneralError:54 - 
java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: org.hibernate.proxy.HibernateProxy. Forgot to register a type adapter?
	at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:73)
...snip...
	at com.google.gson.Gson.toJson(Gson.java:623)
	at us.freeandfair.corla.endpoint.ContestDownloadByCounty.endpoint(ContestDownloadByCounty.java:80)
```

```
20:46:06,463 ERROR GeneralError:54 - 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at us.freeandfair.corla.endpoint.AbstractEndpoint.persistLogEntries(AbstractEndpoint.java:430)
	at us.freeandfair.corla.endpoint.AbstractEndpoint.afterAfter(AbstractEndpoint.java:496)
```

**Comment by dmzimmerman** [comment]
Fixed by #453
