### ISSUE TITLE
"unable to publish ballots to audit" failure

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#572]
```16:41:46,523  INFO corla:91 - county 3 initially estimated to audit 294 ballots
16:41:46,599  INFO corla:242 - ASM event COUNTY_START_AUDIT_EVENT caused transition to COUNTY_AUDIT_UNDERWAY
16:41:46,603  INFO corla:242 - ASM event AUDIT_BOARD_START_AUDIT_EVENT caused transition to AUDIT_BOARD_SIGNED_OUT
java.lang.IllegalArgumentException: invalid sequence bounds
	at us.freeandfair.corla.controller.ComparisonAuditController.computeBallotOrder(ComparisonAuditController.java:171)
	at us.freeandfair.corla.controller.ComparisonAuditController.initializeAuditData(ComparisonAuditController.java:248)
	at us.freeandfair.corla.endpoint.PublishBallotsToAudit.endpoint(PublishBallotsToAudit.java:90)
	at us.freeandfair.corla.Main.lambda$activateEndpoints$5(Main.java:253)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
16:41:46,620 ERROR corla:443 - error 500 server error on /ballots-to-audit/publish: could not set ballot list for county 4 by stateadmin1 from localhost:8888
```

**Comment by kiniry** [comment]
Looks like it has to do with not selecting a contest to audit in all counties under audit.
