### ISSUE TITLE
NPE triggered by rapid server interaction

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#858]
@ranweiler wrote on Slack:

```
00:07:41,502  INFO corla:406 - endpoint /ballot-not-found hit by localhost:8888
00:07:41,531 ERROR corla:462 - uncaught exception in endpoint /ballot-not-found:
java.lang.NullPointerException
    at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
    at us.freeandfair.corla.model.CVRAuditInfo.setDisagreement(CVRAuditInfo.java:253)
    at us.freeandfair.corla.controller.ComparisonAuditController.unaudit(ComparisonAuditController.java:730)
    at us.freeandfair.corla.controller.ComparisonAuditController.submitAuditCVR(ComparisonAuditController.java:536)
    at us.freeandfair.corla.endpoint.BallotNotFound.endpointBody(BallotNotFound.java:145)
    at us.freeandfair.corla.endpoint.AbstractEndpoint.endpoint(AbstractEndpoint.java:454)
    at us.freeandfair.corla.Main.lambda$activateEndpoints$5(Main.java:375)
    at spark.RouteImpl$1.handle(RouteImpl.java:72)
    at spark.http.matching.Routes.execute(Routes.java:61)
    at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
    at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:564)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
    at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
    at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
    at java.lang.Thread.run(Thread.java:748)

00:07:41,532 ERROR corla:506 - error 500 server error on /ballot-not-found: java.lang.NullPointerException by countyadmin1 from localhost:8888
```
with file:
```
File name: d0-n50000.csv

SHA-256 hash: 16740B3A7FFB5AC4E42764CD775300285D5AC7E6FEE1E91B956ABF5ABDB73B9B
```

all i did was click "Ballot not found" a bunch of times really fast
it accepted 2, then failed with NPEs for every other attempt

**Comment by dmzimmerman** [comment]
For some reason, this resulted in the client submitting "ballot not found" for the same ballot a lot of times... that's probably something to look into.
